### ISSUE TITLE
Dozens of errors per second in tornado handler

### ISSUE THREAD

**Issue by homm** [rollbar/pyrollbar#129]
We used rollbar with default threaded handler for tornado application for a long while and recently have switched to tornado handler and faced with the following error after some time (2-3 days). Server logs were full of errors with frequency several dozens per second. The application eats about 5-6 Gigs of memory:

```
Sep 09 02:18:42:  ERROR:tornado.application:Future exception was never retrieved: Traceback (most recent call last):
Sep 09 02:18:42:    File "/env/local/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
Sep 09 02:18:42:      yielded = self.gen.throw(*exc_info)
Sep 09 02:18:42:    File "/env/local/lib/python2.7/site-packages/rollbar/__init__.py", line 1167, in _post_api_tornado
Sep 09 02:18:42:      request_timeout=SETTINGS.get('timeout', DEFAULT_TIMEOUT)
Sep 09 02:18:42:    File "/env/local/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
Sep 09 02:18:42:      value = future.result()
Sep 09 02:18:42:    File "/env/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
Sep 09 02:18:42:      raise_exc_info(self._exc_info)
Sep 09 02:18:42:    File "<string>", line 3, in raise_exc_info
Sep 09 02:18:42:  HTTPError: HTTP 599: Timeout
```

We are handling errors via logging errors:

```python
import logging.handlers

import rollbar.logger

from tornado import log
from tornado.httputil import HTTPServerRequest

class TornadoRollbarHandler(rollbar.logger.RollbarHandler):
    def emit(self, record):
        if record.name == 'tornado.application':
            if len(record.args) >= 2:
                request = record.args[1]
                if isinstance(request, HTTPServerRequest):
                    record.request = request

        return super(TornadoRollbarHandler, self).emit(record)


rollbar.init(**{
    'enabled': False,
    'access_token': 'xxx',
    'environment': ENVIRONMENT,
    'handler': 'tornado',
    'allow_logging_basic_config': False,
})

rollbar_handler = TornadoRollbarHandler(history_level=logging.INFO)
rollbar_handler.setLevel(logging.ERROR)
rollbar_handler.addFilter(ExcludeFilter('tornado.access'))
logging.root.addHandler(rollbar_handler)
```

python==2.7.6
tornado==4.3.0
rollbar==0.13.2

**Comment by coryvirok** [comment]
Hello @homm,

I haven't tested this but I think the problem might be that we aren't checking for an error when we call `fetch()` and Tornado is making sure that we aren't just swallowing exceptions. Here's the code in Tornado that appears to be checking if we have checked for the presence of an exception and throwing this error in the case where we don't check: http://www.tornadoweb.org/en/stable/concurrent.html#tornado.concurrent.Future

Here's a question which seems related:
http://stackoverflow.com/questions/7549120/exception-handling-in-python-tornado

I think a solution might be to check for the presence of an error here: https://github.com/rollbar/pyrollbar/blob/master/rollbar/__init__.py#L1170 and rethrowing it.
