### ISSUE TITLE
Reporting an exception whose __str__ throws an exception fails

### ISSUE THREAD

**Issue by nornagon** [rollbar/pyrollbar#148]
To reproduce:

```python
class BrokenError(Exception):
  def __str__(self):
    raise ValueError("I'm dumb")

try:
  raise BrokenError()
except:
  rollbar.report_exc_info(sys.exc_info())
```

The exception never makes it to Rollbar, and gets lost in the log noise.

Relevant part of the traceback:

```
Traceback (most recent call last):
  File "/home/ubuntu/product/env/lib/python3.4/site-packages/rollbar/__init__.py", line 354, in report_exc_info
    return _report_exc_info(exc_info, request, extra_data, payload_data, level=level)
  File "/home/ubuntu/product/env/lib/python3.4/site-packages/rollbar/__init__.py", line 586, in _report_exc_info
    'message': text(exc),
  File "/home/ubuntu/product/env/lib/python3.4/site-packages/rollbar/lib/__init__.py", line 60, in text
    return str(val)
```

Using pyrollbar 0.13.8.

**Comment by ezarowny** [comment]
Hey @nornagon thanks for reporting this - it's quite interesting!

**Comment by ezarowny** [comment]
Ah, I think the solution here is to put a detailed string in place of the message here. Maybe something along the lines of https://github.com/rollbar/pyrollbar/blob/master/rollbar/lib/__init__.py#L196-L198.

**Comment by coryvirok** [comment]
Ya, we will need to add in exception handlers to these serialize methods - https://github.com/rollbar/pyrollbar/blob/master/rollbar/lib/transforms/serializable.py#L41
