### ISSUE TITLE
scrapy & pyrollbar integration issue 'cannot deepcopy this pattern object'

### ISSUE THREAD

**Issue by anthonylau** [rollbar/pyrollbar#158]
I want to use rollbar in my scrapy project, but seems rollbar unable to serialize scrapy's object.
Does anyone know if there is a better way to integrate?

How I integrate scrapy & pyrollbar, in spider's `__init__`
```
handler = RollbarHandler(access_token=settings.ROLLBAR_TOKEN, environment=settings.ROLLBAR_ENV, level=logging.WARNING)
logging.getLogger('scrapy').addHandler(handler)
logging.getLogger('twisted').addHandler(handler)
self.logger.logger.addHandler(handler)
```

Versions
```
Scrapy==1.3.2
rollbar==0.13.11
```

Trace
```
2017-03-03 09:33:23 [rollbar] ERROR: Exception while reporting exc_info to Rollbar. TypeError('cannot deepcopy this pattern object',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/rollbar/__init__.py", line 354, in report_exc_info
    return _report_exc_info(exc_info, request, extra_data, payload_data, level=level)
  File "/usr/local/lib/python3.5/site-packages/rollbar/__init__.py", line 604, in _report_exc_info
    data = dict_merge(data, payload_data)
  File "/usr/local/lib/python3.5/site-packages/rollbar/lib/__init__.py", line 173, in dict_merge
    result[k] = dict_merge(result[k], v)
  File "/usr/local/lib/python3.5/site-packages/rollbar/lib/__init__.py", line 175, in dict_merge
    result[k] = copy.deepcopy(v)
  File "/usr/local/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/local/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.5/copy.py", line 250, in _deepcopy_method
    return type(x)(x.__func__, deepcopy(x.__self__, memo))
  File "/usr/local/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.5/copy.py", line 223, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/local/lib/python3.5/copy.py", line 223, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/local/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.5/copy.py", line 166, in deepcopy
    y = copier(memo)
TypeError: cannot deepcopy this pattern object
```

**Comment by coryvirok** [comment]
I think I see what's wrong here. It looks like our `dict_merge()` implementation doesn't gracefully handle copying things which cannot be copied. I'm honestly surprised I haven't seen this come up yet. I think the correct-ish solution is to add in a new label for things which cannot be copied like we have for [un-encodable objects](https://github.com/rollbar/pyrollbar/blob/master/rollbar/lib/__init__.py#L196). We would then catch the `TypeError` in `dict_merge()` and use the new label in its place.

@rokob ?

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
