### ISSUE TITLE
Rollbar not working on aws lambda.

### ISSUE THREAD

**Issue by amajeed-dinCloud** [rollbar/pyrollbar#167]
I am trying to use rollbar with aws lambda. I am getting following error.

[1496632728018] [ERROR] 2017-06-05T03:18:47.999Z b08c5791-499d-11e7-9821-6fdd89621437 Exception while posting item ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.rollbar.com', port=443): Max retries exceeded with url: /api/1/item/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f625e633c50>: Failed to establish a new connection: [Errno 1] Operation not permitted',))",),)
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\skillsaga-content_curation\venv\lib\site-packages\rollbar\__init__.py", line 1104, in _send_payload
  File "C:\Users\Administrator\PycharmProjects\skillsaga-content_curation\venv\lib\site-packages\rollbar\__init__.py", line 1145, in _post_api
  File "/var/task/rollbar/lib/transport.py", line 7, in post
  return _session.post(*args, **kw)
  File "C:\Users\Administrator\AppData\Local\Temp\pycharm-packaging0.tmp\requests\requests\sessions.py", line 535, in post
  File "C:\Users\Administrator\AppData\Local\Temp\pycharm-packaging0.tmp\requests\requests\sessions.py", line 488, in request
  File "C:\Users\Administrator\AppData\Local\Temp\pycharm-packaging0.tmp\requests\requests\sessions.py", line 609, in send
  File "C:\Users\Administrator\AppData\Local\Temp\pycharm-packaging0.tmp\requests\requests\adapters.py", line 487, in send

**Comment by ezarowny** [comment]
Are you still having this issue?

**Comment by amajeed-dinCloud** [comment]
Exceptions are being logged now but it takes more time then usual (compare to local environment). What was the cause of it??

**Comment by ezarowny** [comment]
We had some API issues yesterday. You can check http://status.rollbar.com/ for some details.

**Comment by amajeed-dinCloud** [comment]
Thank you.
