### ISSUE TITLE
Flask throws `working outside request context`

### ISSUE THREAD

**Issue by pmatos** [rollbar/pyrollbar#177]
I have a command line Python app which doesn't use Flask or any other web framework, however I still manage to see (with rollbar `0.13.11`):
```
 ERROR:rollbar:Exception while building person data for Rollbar payload: RuntimeError('working outside of request context',)
Traceback (most recent call last):
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/rollbar/__init__.py", line 683, in _add_person_data
    person_data = _build_person_data(request)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/rollbar/__init__.py", line 697, in _build_person_data
    if hasattr(request, 'rollbar_person'):
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/werkzeug/local.py", line 297, in _get_current_object
    return self.__local()
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/flask/globals.py", line 20, in _lookup_req_object
    raise RuntimeError('working outside of request context')
RuntimeError: working outside of request context
```

This is what I have:
```
import os
import sys
import logging
import rollbar
from rollbar.logger import RollbarHandler

rollbar.init(KEY,
             environment='development',
             allow_logging_basic_config=True)

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# report ERROR and above to Rollbar
rollbar_handler = RollbarHandler()
rollbar_handler.setLevel(logging.ERROR)

# attach the handlers to the root logger
logger.addHandler(rollbar_handler)

logger.critical(__name__)
logger.error('test error')
logger.debug('test debug')
logger.info('test info')
logger.critical('test critical')
logger.info('test warning')
```

**Comment by pmatos** [comment]
Same with `0.13.12`:
```
Traceback (most recent call last):
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/rollbar/__init__.py", line 686, in _add_person_data
    person_data = _build_person_data(request)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/rollbar/__init__.py", line 700, in _build_person_data
    if hasattr(request, 'rollbar_person'):
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/werkzeug/local.py", line 297, in _get_current_object
    return self.__local()
  File "/home/pmatos/.pyenv/versions/3.6.0/envs/cfd-venv/lib/python3.6/site-packages/flask/globals.py", line 20, in _lookup_req_object
    raise RuntimeError('working outside of request context')
RuntimeError: working outside of request context
```

**Comment by coryvirok** [comment]
Interesting. I think what is happening is that Rollbar is detecting that you have Flask installed and is attempting to use the Flask integration. Can you verify that Flask is installed in the virtualenv you're using?

The quick-n-dirty solution is to uninstall Flask if you're not using it.

**Comment by rivkahstandig3636** [comment]
This is the same issue as #207. Since there hasn't been any activity on this issue since July, I'll close this one in favor of the new issue.
