### ISSUE TITLE
Exception while reporting exc_info to Rollbar. TypeError("can't pickle select.epoll objects",)

### ISSUE THREAD

**Issue by 31z4** [rollbar/pyrollbar#210]
I'm using `rollbar==0.13.16` with `tornado==4.5.2` and getting the following exception:

```
[E 171025 05:47:48 __init__:411] Exception while reporting message to Rollbar. TypeError("can't pickle select.epoll objects",)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/project-ps-hsm/src/handlers/balance.py", line 21, in get
        yield self.check_blacklist()
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/project-ps-hsm/src/handlers/_base.py", line 81, in check_blacklist
        reason = yield is_blacklisted(self.can, self.current_user)
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/project-ps-hsm/src/utils/afp_processing.py", line 42, in is_blacklisted
        'SECRET': config.INTERNAL_API_SECRET['customer'],
      File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
    tornado.httpclient.HTTPError: HTTP 500: Internal Server Error
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/rollbar/__init__.py", line 409, in report_message
        return _report_message(message, level, request, extra_data, payload_data)
      File "/usr/local/lib/python3.6/site-packages/rollbar/__init__.py", line 712, in _report_message
        data = dict_merge(data, payload_data)
      File "/usr/local/lib/python3.6/site-packages/rollbar/lib/__init__.py", line 174, in dict_merge
        result[k] = dict_merge(result[k], v)
      File "/usr/local/lib/python3.6/site-packages/rollbar/lib/__init__.py", line 176, in dict_merge
        result[k] = copy.deepcopy(v)
      File "/usr/local/lib/python3.6/copy.py", line 150, in deepcopy
        y = copier(x, memo)
      File "/usr/local/lib/python3.6/copy.py", line 215, in _deepcopy_list
        append(deepcopy(a, memo))
      File "/usr/local/lib/python3.6/copy.py", line 150, in deepcopy
        y = copier(x, memo)
      File "/usr/local/lib/python3.6/copy.py", line 240, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/local/lib/python3.6/copy.py", line 150, in deepcopy
        y = copier(x, memo)
      File "/usr/local/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
        y = [deepcopy(a, memo) for a in x]
      File "/usr/local/lib/python3.6/copy.py", line 220, in <listcomp>
        y = [deepcopy(a, memo) for a in x]
      File "/usr/local/lib/python3.6/copy.py", line 180, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/usr/local/lib/python3.6/copy.py", line 280, in _reconstruct
        state = deepcopy(state, memo)
      File "/usr/local/lib/python3.6/copy.py", line 150, in deepcopy
        y = copier(x, memo)
      File "/usr/local/lib/python3.6/copy.py", line 240, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/local/lib/python3.6/copy.py", line 180, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/usr/local/lib/python3.6/copy.py", line 280, in _reconstruct
        state = deepcopy(state, memo)
      File "/usr/local/lib/python3.6/copy.py", line 150, in deepcopy
        y = copier(x, memo)
      File "/usr/local/lib/python3.6/copy.py", line 240, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/local/lib/python3.6/copy.py", line 180, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/usr/local/lib/python3.6/copy.py", line 280, in _reconstruct
        state = deepcopy(state, memo)
      File "/usr/local/lib/python3.6/copy.py", line 150, in deepcopy
        y = copier(x, memo)
      File "/usr/local/lib/python3.6/copy.py", line 240, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/local/lib/python3.6/copy.py", line 180, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/usr/local/lib/python3.6/copy.py", line 280, in _reconstruct
        state = deepcopy(state, memo)
      File "/usr/local/lib/python3.6/copy.py", line 150, in deepcopy
        y = copier(x, memo)
      File "/usr/local/lib/python3.6/copy.py", line 240, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/local/lib/python3.6/copy.py", line 169, in deepcopy
        rv = reductor(4)
    TypeError: can't pickle select.epoll objects
```

It results in certain errors don't show up in Rollbar which is pretty bad 😞 
It seems like not every `exc_info` is pickable and this situation should be handled properly. I suggest still reporting the error message, even without the exception info.

**Comment by rokob** [comment]
I'm looking into the right place to fix this, will update here when I have something.

**Comment by 31z4** [comment]
Thanks for the swift response on that @rokob. I left a comment in the PR 🙂

**Comment by 31z4** [comment]
Also, could you please provide any ETA for releasing a version with the fix? Or it's safe to install from `master`?

**Comment by rokob** [comment]
I will make a release tomorrow
