### ISSUE TITLE
Regression in 0.13.17 when `payload_data` is supplied without `'body'`

### ISSUE THREAD

**Issue by benkuhn** [rollbar/pyrollbar#217]
Hi--we recently had to downgrade to 0.13.16 due to a KeyError in [`__init__.py` line 630](https://github.com/rollbar/pyrollbar/blob/v0.13.17/rollbar/__init__.py#L630):

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rollbar/__init__.py", line 393, in report_exc_info
    return _report_exc_info(exc_info, request, extra_data, payload_data, level=level)
  File "/usr/local/lib/python3.6/site-packages/rollbar/__init__.py", line 630, in _report_exc_info
    if payload_data and payload_data['body'] and payload_data['body']['trace']:
KeyError: 'body'```

The problem is that we're calling `_report_exc_info` with `payload_data` that doesn't have a `'body'` key.

**Comment by hwright** [comment]
@rokob Any chance of getting a release with this fix in it?
