### ISSUE TITLE
[Django] ERROR: Exception while reporting exc_info to Rollbar. UnicodeEncodeError('ascii', ...

### ISSUE THREAD

**Issue by 7wonders** [rollbar/pyrollbar#49]
Getting the following error.
```
Traceback (most recent call last):

  File "/app/.heroku/python/lib/python2.7/site-packages/rollbar/__init__.py", line 262, in report_exc_info
    return _report_exc_info(exc_info, request, extra_data, payload_data, level=level)

  File "/app/.heroku/python/lib/python2.7/site-packages/rollbar/__init__.py", line 491, in _report_exc_info
    'message': str(exc),

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 23: ordinal not in range(128)


Request repr() unavailable.
```

**Comment by brianr** [comment]
Thanks @7wonders for the report. We'll get this fixed.
