### ISSUE TITLE
v0.9.14 [Django] ERROR: Exception while posting item

### ISSUE THREAD

**Issue by 7wonders** [rollbar/pyrollbar#70]
```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/rollbar/__init__.py", line 1093, in _send_payload
    _post_api('item/', payload, access_token=payload.get('access_token'))
  File "/app/.heroku/python/lib/python2.7/site-packages/rollbar/__init__.py", line 1130, in _post_api
    payload = ErrorIgnoringJSONEncoder().encode(payload)
  File "/app/.heroku/python/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/app/.heroku/python/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 262: invalid start byte
```

**Comment by coryvirok** [comment]
Hi @7wonders. Thanks for the bug report. We will take a look.

**Comment by rivkahstandig3636** [comment]
Closing as we have had no further reports of this in over 2 years.
