### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by suhaasprasad** [rollbar/pyrollbar#90]
Seeing a UnicodeEncodeError when trying to report an error on Google App Engine:

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/__init__.py", line 402, in report_exc_info
    return _report_exc_info(exc_info, request, extra_data, payload_data, level=level)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/__init__.py", line 651, in _report_exc_info
    payload = _build_payload(data)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/__init__.py", line 1144, in _build_payload
    data[k] = _transform(v, key=(k,))
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/__init__.py", line 1135, in _transform
    return transforms.transform(obj, _transforms, key=key)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/transforms/__init__.py", line 107, in transform
    return traverse.traverse(obj, key=key, **handlers)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/traverse.py", line 128, in traverse
    return mapping_handler(dict((k, traverse(v, key=key + (k,), **kw)) for k, v in iteritems(obj)), key=key)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/traverse.py", line 128, in <genexpr>
    return mapping_handler(dict((k, traverse(v, key=key + (k,), **kw)) for k, v in iteritems(obj)), key=key)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/traverse.py", line 128, in traverse
    return mapping_handler(dict((k, traverse(v, key=key + (k,), **kw)) for k, v in iteritems(obj)), key=key)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/traverse.py", line 128, in <genexpr>
    return mapping_handler(dict((k, traverse(v, key=key + (k,), **kw)) for k, v in iteritems(obj)), key=key)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/traverse.py", line 124, in traverse
    return list_handler(list(traverse(elem, key=key + (i,), **kw) for i, elem in enumerate(obj)), key=key)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/traverse.py", line 124, in <genexpr>
    return list_handler(list(traverse(elem, key=key + (i,), **kw) for i, elem in enumerate(obj)), key=key)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/traverse.py", line 128, in traverse
    return mapping_handler(dict((k, traverse(v, key=key + (k,), **kw)) for k, v in iteritems(obj)), key=key)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/traverse.py", line 128, in <genexpr>
    return mapping_handler(dict((k, traverse(v, key=key + (k,), **kw)) for k, v in iteritems(obj)), key=key)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/traverse.py", line 128, in traverse
    return mapping_handler(dict((k, traverse(v, key=key + (k,), **kw)) for k, v in iteritems(obj)), key=key)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/traverse.py", line 128, in <genexpr>
    return mapping_handler(dict((k, traverse(v, key=key + (k,), **kw)) for k, v in iteritems(obj)), key=key)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/traverse.py", line 118, in traverse
    return string_handler(obj, key=key)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/transforms/__init__.py", line 77, in string_handler
    return do_transforms('unicode', s, key=key)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/transforms/__init__.py", line 68, in do_transforms
    val = fn(val, key=key, **kw)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/transforms/__init__.py", line 52, in transform_unicode
    return self.default(o, key=key)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/transforms/scruburl.py", line 89, in default
    return super(ScrubUrlTransform, self).default(o, key=key)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/transforms/scrub.py", line 31, in default
    return self.redact(o)
  File "/base/data/home/apps/s~revfluenceapp/1.390286199091920271/app/common/lib/rollbar/lib/transforms/scruburl.py", line 62, in redact
    scrubbed_qs = urlencode(qs_params, doseq=True)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib.py", line 1332, in urlencode
    l.append(k + '=' + quote_plus(str(elt)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
```

**Comment by brianr** [comment]
Thanks for the report. What version of pyrollbar and python are you running?

**Comment by coryvirok** [comment]
Not sure if this is still happening but I've tagged it as a bug so we can at least test.

**Comment by rivkahstandig3636** [comment]
Closing as we have had no further reports of this or any response from suhaasprasad.
